### PR TITLE
updated the intro explanation to clustering.ipynb

### PR DESCRIPTION
**Pull request by yoid2000**
I also ran both clustering.ipynb and tutorial.ipynb, which created a lot of changes

### CODE REVIEW

**Comment by cristianberneanu** [comment]
There is a lot of noise here because of the changes that appear when re-running a notebook. You can select individual changes to add to a commit by executing:
```
git add -p docs/clustering.ipynb
```
After the commit is made, you can drop the unwanted changes from the file with:
```
git checkout docs/clustering.ipynb
```

**Comment by yoid2000** [comment]
Should I try that now, or is it too late?

**Comment by edongashi** [comment]
Changes look fine. I'd get rid of the installation messages.

> Should I try that now, or is it too late?

If you want to, we can force push the branch with only relevant changes, or we can create a new cleaned up PR.

**Comment by cristianberneanu** [comment]
It isn't too late, since it wasn't merged.
You can restart the previous commit by executing:
```
git reset HEAD^
```
Also, you can manually clear notebook cells with useless outptut (like the ones for installing packages).

**Pull request closed without merging**
