### PR TITLE
Forest snapshot tests

### PR DESCRIPTION
**Pull request by edongashi**
Instead of comparing huge trees manually, I made assertions that hashes are identical with F#.

### CODE REVIEW

**Comment by edongashi** [comment]
Cristian what do you think about this idea? I want tests for consistency across all stages...

These hashes match with syndiffix https://github.com/diffix/syndiffix/pull/27

**Comment by cristianberneanu** [comment]
> Cristian what do you think about this idea? I want tests for consistency across all stages...
> 
> These hashes match with syndiffix [diffix/syndiffix#27](https://github.com/diffix/syndiffix/pull/27)

I think they are very opaque and hard to debug. Even worse, they are also tied to the code from another repository.

As you said, they will catch some bugs, like when trying to optimize something without changing behavior. But any change in behavior means updating a hash value blindly.

Ideally, data would be generated dynamically (I know, easier said than done), it should be smaller and only 2 or 3 columns should be used, so we can have a chance to understand the resulting trees.

Besides these, the biggest improvement for the current version that I see would be to drop the hashing and include the tree-to-string dumps in a json/txt file, so we can diff it between different commits.

**Comment by edongashi** [comment]
Ok, I will revisit after I actually catch what is causing our issues. Forests look OK in any case.

> Ideally, data would be generated dynamically

I'm trying to do something like this for stitching. So far it looks like it's working as expected, which leaves us with harvesting and microdata.

**Comment by edongashi** [comment]
Attempt nr. 2 with a much simpler file. It might even be a little _too simple_ to be of use. But we can follow this pattern with particular test cases in the future. For now I leave this here. When I get the chance I will make similar changes to dep. measure.

**Review by cristianberneanu — APPROVED** [review]

**Pull request merged**
