### PR TITLE
Make an alpha release.

### LINKED ISSUE #84: Set up pipeline for pip publication
Initially an alpha version.

### PR DESCRIPTION
**Pull request by cristianberneanu**
Closes #84.

### CODE REVIEW

**Comment by edongashi** [comment]
Can you handle #95 here so that we don't deploy the unnecessary dep and file?

**Comment by edongashi** [comment]
I guess it's `poetry remove fire` and `rm src/__main__.py`. Unless it breaks something...

**Comment by cristianberneanu** [comment]
Sure, I'll fix it here.

**Comment by cristianberneanu** [comment]
Also closes #95.

**Comment by edongashi** [comment]
Build is failing.

**Comment by cristianberneanu** [comment]
> Build is failing.

Now it is ready for review.

**Review by edongashi — APPROVED** [review]

**Pull request merged**
