### PR TITLE
Added check for safe string values

### PR DESCRIPTION
**Pull request by yoid2000**
Note that the new code in `synthesizer.py` assumes that the ordering of columns in the dataframe is the same as the ordering of convertors as well as the ordering of 1dim tree combinations

### CODE REVIEW

**Review by cristianberneanu — APPROVED** [review]

**Comment by cristianberneanu** [comment]
```
./syndiffix/microdata.py:[12](https://github.com/diffix/syndiffix/actions/runs/7572899122/job/20623798601?pr=131#step:9:13)8:121: E501 line too long (257 > 120 characters)
./tests/test_microdata.py:20:121: E501 line too long (238 > 120 characters)
./tests/test_microdata.py:37:121: E501 line too long (189 > 120 characters)
./tests/test_microdata.py:236:121: E501 line too long (125 > 120 characters)
```
Some of the lines are longer than 120 characters.

**Comment by yoid2000** [comment]
Christion, which tool exposed those longer lines?

**Comment by yoid2000** [comment]
@cristianberneanu could you have a quick look at the changes in `algorithm.md` and to see if they make sense to you? If so, then all checks have passed and I'm ready to merge.

**Comment by cristianberneanu** [comment]
> Christion, which tool exposed those longer lines?

These errors appear when running `flake8`.

**Review by cristianberneanu — APPROVED** [review]
Looks good to me.

**Pull request merged**
