### PR TITLE
Refactor and improve development docs.

### PR DESCRIPTION
**Pull request by cristianberneanu**

### CODE REVIEW

**Review by yoid2000 — CHANGES_REQUESTED** [review]
Could you also keep the pointers to the step-by-step description and the arxiv paper in the main README.md, under a heading "Additional information" or something (but keep them in development.md as well). That information is of interest to both users and developers. (If you'd prefer that that is in one place only, I'd prefer keeping it int he main README.md.

**Comment by cristianberneanu** [comment]
How about if I put a link to the development.md file in the Readme?

**Comment by yoid2000** [comment]
A link to the development page in the readme is in any event a good idea. But I still would like direct pointers to the arxiv and the algorithm in the readme. They are of general interest, not just to developers.

**Review by yoid2000 — APPROVED** [review]
Thanks!

**Pull request merged**
